name: bethriftytoday
description: A simple money management app for those who want to be in control of their financial life.

version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  cloud_firestore: ^0.13.4
  encrypt: ^4.0.0
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+2
  firebase_messaging: ^6.0.12
  google_sign_in: ^4.1.4
  intl: ^0.16.1
  json_annotation: ^3.0.1
  local_auth: ^0.6.1+3
  package_info: ^0.4.0+14
  provider: ^4.0.4
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+2
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  flutter_launcher_icons: ^0.7.4
  json_serializable: ^3.2.5

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/categories/expense/
    - assets/categories/income/
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/FiraSans-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/FiraSans-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/FiraSans-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-ExtraBold-800.ttf
          weight: 800
